apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab7
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: .
    repoURL: https://github.com/elecshen/k8s-argoCD.git
    targetRevision: main
  destination:
    namespace: lab7
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
